
spring.application.name=api-gateway

server.port=8080

#################################################
# Gateway Routes
#################################################

spring.cloud.gateway.server.webflux.routes[0].id=simple-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://172.23.158.99:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/hello                                                                                   vvnv bn vbb nbbbbb/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1



#################################################
# Logging
#################################################
m
logging.level.org.springframework.cloud.gateway=DEBUG

#################################################
# Actuator
#################################################

management.endpoints.web.exposure.include=*

#################################################
# Eureka
#################################################

eureka.client.service-url.defaultZone=http://172.23.158.36:8761/eureka/

eureka.instance.prefer-ip-address=true